perl -p -i -e 's/mepr_gateway_paths/mepr_cpt_model_url/g' mepr_cpt_model_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_get_job_attribute_/g' mepr_get_job_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_set_job_attribute_/g' mepr_set_job_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_view_paths_get_string_/g' mepr_view_paths_get_string_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_view_paths_get_string/g' mepr_view_paths_get_string.md
perl -p -i -e 's/mepr_gateway_paths/mepr_view_get_string_/g' mepr_view_get_string_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_view_get_string/g' mepr_view_get_string.md
perl -p -i -e 's/mepr_gateway_paths/mepr_view_paths/g' mepr_view_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_email_paths/g' mepr_email_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_job_paths/g' mepr_job_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_email_send_params/g' mepr_email_send_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_email_plaintext_body/g' mepr_email_plaintext_body.md
perl -p -i -e 's/mepr_gateway_paths/mepr_email_html_body/g' mepr_email_html_body.md
perl -p -i -e 's/mepr_gateway_paths/mepr_ctrls_paths/g' mepr_ctrls_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_jobs_config/g' mepr_jobs_config.md
perl -p -i -e 's/mepr_gateway_paths/mepr_upgraded__sub/g' mepr_upgraded__sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_upgraded_sub/g' mepr_upgraded_sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_sub_created/g' mepr_sub_created.md
perl -p -i -e 's/mepr_gateway_paths/mepr_downgraded__sub/g' mepr_downgraded__sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_downgraded_sub/g' mepr_downgraded_sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_sub_created/g' mepr_sub_created.md
perl -p -i -e 's/mepr_gateway_paths/mepr_new__sub/g' mepr_new__sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_new_sub/g' mepr_new_sub.md
perl -p -i -e 's/mepr_gateway_paths/mepr_sub_created/g' mepr_sub_created.md
perl -p -i -e 's/mepr_gateway_paths/mepr_login_title/g' mepr_login_title.md
perl -p -i -e 's/mepr_gateway_paths/mepr_get_model_attribute_/g' mepr_get_model_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_set_model_attribute_/g' mepr_set_model_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_admin_capability/g' mepr_admin_capability.md
perl -p -i -e 's/mepr_gateway_paths/mepr_wp_mail_recipients/g' mepr_wp_mail_recipients.md
perl -p -i -e 's/mepr_gateway_paths/mepr_wp_mail_subject/g' mepr_wp_mail_subject.md
perl -p -i -e 's/mepr_gateway_paths/mepr_wp_mail_message/g' mepr_wp_mail_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_wp_mail_headers/g' mepr_wp_mail_headers.md
perl -p -i -e 's/mepr_gateway_paths/mepr_logout_url/g' mepr_logout_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_transaction_email_vars/g' mepr_transaction_email_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_gateway_notification_params/g' mepr_gateway_notification_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_transaction_email_params/g' mepr_transaction_email_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_invoice/g' mepr_invoice.md
perl -p -i -e 's/mepr_gateway_paths/mepr_invoice_show_quantity/g' mepr_invoice_show_quantity.md
perl -p -i -e 's/mepr_gateway_paths/mepr_invoice_html/g' mepr_invoice_html.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_email_vars/g' mepr_user_email_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_notification_params/g' mepr_user_notification_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_email_params/g' mepr_user_email_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_custom_field_html/g' mepr_custom_field_html.md
perl -p -i -e 's/mepr_gateway_paths/mepr_currency_symbols/g' mepr_currency_symbols.md
perl -p -i -e 's/mepr_gateway_paths/mepr_currency_codes/g' mepr_currency_codes.md
perl -p -i -e 's/mepr_gateway_paths/mepr_language_codes/g' mepr_language_codes.md
perl -p -i -e 's/mepr_gateway_paths/mepr_reminder_notification_vars/g' mepr_reminder_notification_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_reminder_email_vars/g' mepr_reminder_email_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_reminder_notification_params/g' mepr_reminder_notification_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_reminder_email_params/g' mepr_reminder_email_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_subscription_email_vars/g' mepr_subscription_email_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_subscription_email_params/g' mepr_subscription_email_params.md
perl -p -i -e 's/mepr_gateway_paths/mepr_active_nav_tab/g' mepr_active_nav_tab.md
perl -p -i -e 's/mepr_gateway_paths/mepr_price_string/g' mepr_price_string.md
perl -p -i -e 's/mepr_gateway_paths/mepr_rules_cpts/g' mepr_rules_cpts.md
perl -p -i -e 's/mepr_gateway_paths/mepr_search_singles_query/g' mepr_search_singles_query.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_excerpt/g' mepr_unauthorized_excerpt.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_message/g' mepr_unauthorized_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_show_login/g' mepr_unauthorized_show_login.md
perl -p -i -e 's/mepr_gateway_paths/mepr_create_transaction/g' mepr_create_transaction.md
perl -p -i -e 's/mepr_gateway_paths/mepr_update_transaction/g' mepr_update_transaction.md
perl -p -i -e 's/mepr_gateway_paths/mepr_delete_transaction/g' mepr_delete_transaction.md
perl -p -i -e 's/mepr_gateway_paths/mepr_delete_transaction/g' mepr_delete_transaction.md
perl -p -i -e 's/mepr_gateway_paths/mepr_txn_transition_status/g' mepr_txn_transition_status.md
perl -p -i -e 's/mepr_gateway_paths/mepr_txn_store/g' mepr_txn_store.md
perl -p -i -e 's/mepr_gateway_paths/mepr_txn_status_/g' mepr_txn_status_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_pre_store/g' mepr_event_pre_store.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_update/g' mepr_event_update.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_create/g' mepr_event_create.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event/g' mepr_event.md
perl -p -i -e 's/mepr_gateway_paths/mepr_evt_/g' mepr_evt_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_/g' mepr_event_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_store/g' mepr_event_store.md
perl -p -i -e 's/mepr_gateway_paths/mepr_event_destroy/g' mepr_event_destroy.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_product_signup_date_order/g' mepr_user_product_signup_date_order.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_use_customer_address/g' mepr_tax_rate_use_customer_address.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_formatted_address/g' mepr_user_formatted_address.md
perl -p -i -e 's/mepr_gateway_paths/mepr_group_theme_templates_paths/g' mepr_group_theme_templates_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_group_themes_paths/g' mepr_group_themes_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_subscr_transition_status/g' mepr_subscr_transition_status.md
perl -p -i -e 's/mepr_gateway_paths/mepr_subscr_store/g' mepr_subscr_store.md
perl -p -i -e 's/mepr_gateway_paths/mepr_subscr_status_/g' mepr_subscr_status_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_limit_payment_cycles_reached/g' mepr_limit_payment_cycles_reached.md
perl -p -i -e 's/mepr_gateway_paths/mepr_found_tax_rate/g' mepr_found_tax_rate.md
perl -p -i -e 's/mepr_gateway_paths/mepr_find_tax_rate/g' mepr_find_tax_rate.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_update/g' mepr_tax_rate_update.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_create/g' mepr_tax_rate_create.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_store/g' mepr_tax_rate_store.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_destroy/g' mepr_tax_rate_destroy.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_location_create/g' mepr_tax_rate_location_create.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_locations_destroy/g' mepr_tax_rate_locations_destroy.md
perl -p -i -e 's/mepr_gateway_paths/mepr_options_dynamic_attrs/g' mepr_options_dynamic_attrs.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_message/g' mepr_unauthorized_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_grace_init_days/g' mepr_grace_init_days.md
perl -p -i -e 's/mepr_gateway_paths/mepr_grace_init_days/g' mepr_grace_init_days.md
perl -p -i -e 's/mepr_gateway_paths/mepr_grace_expire_days/g' mepr_grace_expire_days.md
perl -p -i -e 's/mepr_gateway_paths/mepr_options_get_dynamic_attribute_/g' mepr_options_get_dynamic_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_options_set_dynamic_attribute_/g' mepr_options_set_dynamic_attribute_.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_login_link_text/g' mepr_unauthorized_login_link_text.md
perl -p -i -e 's/mepr_gateway_paths/mepr_extra_profile_fields/g' mepr_extra_profile_fields.md
perl -p -i -e 's/mepr_gateway_paths/mepr_partial_content_codes/g' mepr_partial_content_codes.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_message_options/g' mepr_unauthorized_message_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_report_footer/g' mepr_report_footer.md
perl -p -i -e 's/mepr_gateway_paths/mepr_report_footer/g' mepr_report_footer.md
perl -p -i -e 's/mepr_gateway_paths/mepr_display_options_tabs/g' mepr_display_options_tabs.md
perl -p -i -e 's/mepr_gateway_paths/mepr_integration_options/g' mepr_integration_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_display_autoresponders/g' mepr_display_autoresponders.md
perl -p -i -e 's/mepr_gateway_paths/mepr_display_general_options/g' mepr_display_general_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_display_options/g' mepr_display_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_rate_options/g' mepr_tax_rate_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_tax_options/g' mepr_tax_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_options_tabs/g' mepr_product_options_tabs.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_options_pages/g' mepr_product_options_pages.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_advanced_metabox/g' mepr_product_advanced_metabox.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_registration_metabox/g' mepr_product_registration_metabox.md
perl -p -i -e 's/mepr_gateway_paths/mepr_after_password_fields/g' mepr_after_password_fields.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_signup_fields/g' mepr_user_signup_fields.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_nav_home_link/g' mepr_account_nav_home_link.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_nav_subscriptions_link/g' mepr_account_nav_subscriptions_link.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_nav_payments_link/g' mepr_account_nav_payments_link.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_nav/g' mepr_account_nav.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_payment_product_name/g' mepr_account_payment_product_name.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_payment_product_name/g' mepr_account_payment_product_name.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_payments/g' mepr_account_payments.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_welcome_message/g' mepr_account_welcome_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_message/g' mepr_user_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_home_fields/g' mepr_account_home_fields.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_home/g' mepr_account_home.md
perl -p -i -e 's/mepr_gateway_paths/mepr_before_account_subscriptions/g' mepr_before_account_subscriptions.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_subscr_product_name/g' mepr_account_subscr_product_name.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_subscr_product_name/g' mepr_account_subscr_product_name.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_subscriptions_table/g' mepr_account_subscriptions_table.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_subscriptions/g' mepr_account_subscriptions.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_password/g' mepr_account_password.md
perl -p -i -e 's/mepr_gateway_paths/mepr_pre_run_rule_redirection/g' mepr_pre_run_rule_redirection.md
perl -p -i -e 's/mepr_gateway_paths/mepr_rule_do_redirection/g' mepr_rule_do_redirection.md
perl -p -i -e 's/mepr_gateway_paths/mepr_pre_run_rule_content/g' mepr_pre_run_rule_content.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_login_form/g' mepr_unauthorized_login_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_content/g' mepr_unauthorized_content.md
perl -p -i -e 's/mepr_gateway_paths/mepr_rewrite_rules_no_protect_dirs/g' mepr_rewrite_rules_no_protect_dirs.md
perl -p -i -e 's/mepr_gateway_paths/mepr_rewrite_rules_protect_types/g' mepr_rewrite_rules_protect_types.md
perl -p -i -e 's/mepr_gateway_paths/mepr_rewrite_rules/g' mepr_rewrite_rules.md
perl -p -i -e 's/mepr_gateway_paths/mepr_validate_signup/g' mepr_validate_signup.md
perl -p -i -e 's/mepr_gateway_paths/mepr_track_signup/g' mepr_track_signup.md
perl -p -i -e 's/mepr_gateway_paths/mepr_process_signup/g' mepr_process_signup.md
perl -p -i -e 's/mepr_gateway_paths/mepr__signup/g' mepr__signup.md
perl -p -i -e 's/mepr_gateway_paths/mepr_signup/g' mepr_signup.md
perl -p -i -e 's/mepr_gateway_paths/mepr_signup_checkout_url/g' mepr_signup_checkout_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_payment_failure/g' mepr_payment_failure.md
perl -p -i -e 's/mepr_gateway_paths/mepr_txn_expired/g' mepr_txn_expired.md
perl -p -i -e 's/mepr_gateway_paths/mepr_transaction_expired/g' mepr_transaction_expired.md
perl -p -i -e 's/mepr_gateway_paths/mepr_logout_url/g' mepr_logout_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_login_redirect_url/g' mepr_login_redirect_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_validate_login/g' mepr_validate_login.md
perl -p -i -e 's/mepr_gateway_paths/mepr_process_login_redirect_url/g' mepr_process_login_redirect_url.md
perl -p -i -e 's/mepr_gateway_paths/mepr_bbpress_unauthorized_message/g' mepr_bbpress_unauthorized_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_meta_boxes/g' mepr_product_meta_boxes.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_save_meta/g' mepr_product_save_meta.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_access_string/g' mepr_product_access_string.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_cant_purchase_string/g' mepr_product_cant_purchase_string.md
perl -p -i -e 's/mepr_gateway_paths/mepr_product_admin_enqueue_script/g' mepr_product_admin_enqueue_script.md
perl -p -i -e 's/mepr_gateway_paths/mepr_custom_thankyou_message/g' mepr_custom_thankyou_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_thank_you_page/g' mepr_thank_you_page.md
perl -p -i -e 's/mepr_gateway_paths/mepr_account_nav_content/g' mepr_account_nav_content.md
perl -p -i -e 's/mepr_gateway_paths/mepr_validate_account/g' mepr_validate_account.md
perl -p -i -e 's/mepr_gateway_paths/mepr_save_account/g' mepr_save_account.md
perl -p -i -e 's/mepr_gateway_paths/mepr_user_account_saved/g' mepr_user_account_saved.md
perl -p -i -e 's/mepr_gateway_paths/mepr_hide_cpt_access_column/g' mepr_hide_cpt_access_column.md
perl -p -i -e 's/mepr_gateway_paths/mepr_menu/g' mepr_menu.md
perl -p -i -e 's/mepr_gateway_paths/mepr_unauthorized_message/g' mepr_unauthorized_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_enqueue_scripts/g' mepr_enqueue_scripts.md
perl -p -i -e 's/mepr_gateway_paths/mepr_signup_styles/g' mepr_signup_styles.md
perl -p -i -e 's/mepr_gateway_paths/mepr_signup_scripts/g' mepr_signup_scripts.md
perl -p -i -e 's/mepr_gateway_paths/mepr_textdomain_paths/g' mepr_textdomain_paths.md
perl -p -i -e 's/mepr_gateway_paths/mepr_reminder_save_meta/g' mepr_reminder_save_meta.md
perl -p -i -e 's/mepr_gateway_paths/mepr_mailchimp_add_subscriber_args/g' mepr_mailchimp_add_subscriber_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_validate_options/g' mepr_validate_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_process_options/g' mepr_process_options.md
perl -p -i -e 's/mepr_gateway_paths/mepr_options_admin_enqueue_script/g' mepr_options_admin_enqueue_script.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_payment_args/g' mepr_paypal_pro_payment_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_refund_args/g' mepr_paypal_pro_refund_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_website_payments_pro_subscr_start_ts/g' mepr_paypal_website_payments_pro_subscr_start_ts.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_create_subscriptions_args/g' mepr_paypal_pro_create_subscriptions_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_update_subscription_args/g' mepr_paypal_pro_update_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_payment_form/g' mepr_paypal_pro_payment_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_express_options_form/g' mepr_paypal_express_options_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_send_request_args/g' mepr_paypal_pro_send_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_send_request/g' mepr_paypal_pro_send_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_website_payments_pro_cancel_message/g' mepr_paypal_website_payments_pro_cancel_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_pro_update_payment_profile_args/g' mepr_paypal_pro_update_payment_profile_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_payment_args/g' mepr_stripe_payment_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_refund_args/g' mepr_stripe_refund_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_subscription_args/g' mepr_stripe_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_update_subscription_args/g' mepr_stripe_update_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_suspend_subscription_args/g' mepr_stripe_suspend_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_resume_subscription_args/g' mepr_stripe_resume_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_cancel_subscription_args/g' mepr_stripe_cancel_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_payment_form/g' mepr_stripe_payment_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_create_plan_args/g' mepr_stripe_create_plan_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_customer_args/g' mepr_stripe_customer_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_request_args/g' mepr_stripe_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_stripe_request/g' mepr_stripe_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_refund_args/g' mepr_paypal_std_refund_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_custom_payment_vars/g' mepr_paypal_std_custom_payment_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_payment_vars/g' mepr_paypal_std_payment_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_subscription_vars/g' mepr_paypal_std_subscription_vars.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_standard_options_form/g' mepr_paypal_standard_options_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_send_request_args/g' mepr_paypal_std_send_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_send_request/g' mepr_paypal_std_send_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_std_update_payment_profile_args/g' mepr_paypal_std_update_payment_profile_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_cancel_message/g' mepr_paypal_cancel_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_payment_args/g' mepr_authorize_payment_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_refund_args/g' mepr_authorize_refund_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_auth_card_args/g' mepr_authorize_auth_card_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_create_subscription_args/g' mepr_authorize_create_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_update_subscription_args/g' mepr_authorize_update_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_cancel_subscription_args/g' mepr_authorize_cancel_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_net_payment_form/g' mepr_authorize_net_payment_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_send_aim_request_args/g' mepr_authorize_send_aim_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_send_aim_request/g' mepr_authorize_send_aim_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_send_arb_request_args/g' mepr_authorize_send_arb_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_authorize_send_arb_request/g' mepr_authorize_send_arb_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_payment_args/g' mepr_paypal_ec_payment_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_refund_args/g' mepr_paypal_ec_refund_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_express_subscr_start_ts/g' mepr_paypal_express_subscr_start_ts.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_create_subscription_args/g' mepr_paypal_ec_create_subscription_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_express_options_form/g' mepr_paypal_express_options_form.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_send_request_args/g' mepr_paypal_ec_send_request_args.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_send_request/g' mepr_paypal_ec_send_request.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_cancel_message/g' mepr_paypal_cancel_message.md
perl -p -i -e 's/mepr_gateway_paths/mepr_paypal_ec_update_payment_profile_args/g' mepr_paypal_ec_update_payment_profile_args.md

